remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: https://fenglimg.github.io/skills-github-pages # change this to the name of your repository
